services:
  api:
    build: ./DEV/app/backend
    container_name: lettyquest-api
    environment:
      - APP_ENV=local
      - DATABASE_URL=sqlite:///./data/app.sqlite3
    ports:
      - "8000:8000"
    env_file:
      - DEV/app/backend/.env
    volumes:
      - ./DEV/app/backend:/app # Mapeia o código para hot-reload
      - ./DEV/app/backend/data:/app/data
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
  